-- Supabase PostgreSQL Database Schema for PropertySure

-- Table 1: Contact & Consultation Form Submissions
CREATE TABLE IF NOT EXISTS public.contact_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  city TEXT DEFAULT 'Noida',
  service TEXT DEFAULT 'Home Loan',
  loan_amount TEXT,
  message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table 2: Sell Property Form Submissions
CREATE TABLE IF NOT EXISTS public.sell_property_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  mobile TEXT NOT NULL,
  email TEXT,
  city TEXT DEFAULT 'Noida',
  property_type TEXT DEFAULT 'Apartment',
  property_value TEXT,
  images TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS (Row Level Security) and allow insert for anon/public
ALTER TABLE public.contact_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sell_property_submissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon inserts to contact_submissions" ON public.contact_submissions
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow anon inserts to sell_property_submissions" ON public.sell_property_submissions
  FOR INSERT WITH CHECK (true);
